// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/v1/reflector.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReflectorEvent_EventType int32

const (
	ReflectorEvent_CONNECTION_OPEN      ReflectorEvent_EventType = 0
	ReflectorEvent_CONNECTION_CLOSE     ReflectorEvent_EventType = 1
	ReflectorEvent_DATA_EXCHANGE        ReflectorEvent_EventType = 2
	ReflectorEvent_STREAM_RESUMED       ReflectorEvent_EventType = 3
	ReflectorEvent_POLICY_VIOLATION     ReflectorEvent_EventType = 4
	ReflectorEvent_CERT_ROTATION_NORMAL ReflectorEvent_EventType = 5 // scheduled rotation, same issuer
	ReflectorEvent_CERT_ROTATION_EARLY  ReflectorEvent_EventType = 6 // rotated before expected expiry [ANOMALY]
	ReflectorEvent_CERT_ROTATION_ISSUER ReflectorEvent_EventType = 7 // issuer fingerprint changed [ANOMALY]
	ReflectorEvent_CERT_ROTATION_DOMAIN ReflectorEvent_EventType = 8 // trust domain changed [ANOMALY]
)

// Enum value maps for ReflectorEvent_EventType.
var (
	ReflectorEvent_EventType_name = map[int32]string{
		0: "CONNECTION_OPEN",
		1: "CONNECTION_CLOSE",
		2: "DATA_EXCHANGE",
		3: "STREAM_RESUMED",
		4: "POLICY_VIOLATION",
		5: "CERT_ROTATION_NORMAL",
		6: "CERT_ROTATION_EARLY",
		7: "CERT_ROTATION_ISSUER",
		8: "CERT_ROTATION_DOMAIN",
	}
	ReflectorEvent_EventType_value = map[string]int32{
		"CONNECTION_OPEN":      0,
		"CONNECTION_CLOSE":     1,
		"DATA_EXCHANGE":        2,
		"STREAM_RESUMED":       3,
		"POLICY_VIOLATION":     4,
		"CERT_ROTATION_NORMAL": 5,
		"CERT_ROTATION_EARLY":  6,
		"CERT_ROTATION_ISSUER": 7,
		"CERT_ROTATION_DOMAIN": 8,
	}
)

func (x ReflectorEvent_EventType) Enum() *ReflectorEvent_EventType {
	p := new(ReflectorEvent_EventType)
	*p = x
	return p
}

func (x ReflectorEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReflectorEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_reflector_proto_enumTypes[0].Descriptor()
}

func (ReflectorEvent_EventType) Type() protoreflect.EnumType {
	return &file_api_v1_reflector_proto_enumTypes[0]
}

func (x ReflectorEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReflectorEvent_EventType.Descriptor instead.
func (ReflectorEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_reflector_proto_rawDescGZIP(), []int{0, 0}
}

type ReflectorEvent_IdentityType int32

const (
	ReflectorEvent_UNKNOWN ReflectorEvent_IdentityType = 0
	ReflectorEvent_SPIFFE  ReflectorEvent_IdentityType = 1
	ReflectorEvent_JWT     ReflectorEvent_IdentityType = 2
	ReflectorEvent_MCP     ReflectorEvent_IdentityType = 3
	ReflectorEvent_OTEL    ReflectorEvent_IdentityType = 4
)

// Enum value maps for ReflectorEvent_IdentityType.
var (
	ReflectorEvent_IdentityType_name = map[int32]string{
		0: "UNKNOWN",
		1: "SPIFFE",
		2: "JWT",
		3: "MCP",
		4: "OTEL",
	}
	ReflectorEvent_IdentityType_value = map[string]int32{
		"UNKNOWN": 0,
		"SPIFFE":  1,
		"JWT":     2,
		"MCP":     3,
		"OTEL":    4,
	}
)

func (x ReflectorEvent_IdentityType) Enum() *ReflectorEvent_IdentityType {
	p := new(ReflectorEvent_IdentityType)
	*p = x
	return p
}

func (x ReflectorEvent_IdentityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReflectorEvent_IdentityType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_reflector_proto_enumTypes[1].Descriptor()
}

func (ReflectorEvent_IdentityType) Type() protoreflect.EnumType {
	return &file_api_v1_reflector_proto_enumTypes[1]
}

func (x ReflectorEvent_IdentityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReflectorEvent_IdentityType.Descriptor instead.
func (ReflectorEvent_IdentityType) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_reflector_proto_rawDescGZIP(), []int{0, 1}
}

// ReflectorEvent is a single observed connection or identity event.
type ReflectorEvent struct {
	state     protoimpl.MessageState   `protogen:"open.v1"`
	NodeId    string                   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp *timestamppb.Timestamp   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventType ReflectorEvent_EventType `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=ebpf.reflector.v1.ReflectorEvent_EventType" json:"event_type,omitempty"`
	// Connection 5-tuple
	SourceAddr string `protobuf:"bytes,4,opt,name=source_addr,json=sourceAddr,proto3" json:"source_addr,omitempty"`
	DestAddr   string `protobuf:"bytes,5,opt,name=dest_addr,json=destAddr,proto3" json:"dest_addr,omitempty"`
	Protocol   string `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Identity (populated when extractable)
	SourceIdentity string `protobuf:"bytes,7,opt,name=source_identity,json=sourceIdentity,proto3" json:"source_identity,omitempty"`
	DestIdentity   string `protobuf:"bytes,8,opt,name=dest_identity,json=destIdentity,proto3" json:"dest_identity,omitempty"`
	// Classification
	IdentityType ReflectorEvent_IdentityType `protobuf:"varint,9,opt,name=identity_type,json=identityType,proto3,enum=ebpf.reflector.v1.ReflectorEvent_IdentityType" json:"identity_type,omitempty"`
	// Byte counters
	BytesTx uint64 `protobuf:"varint,10,opt,name=bytes_tx,json=bytesTx,proto3" json:"bytes_tx,omitempty"`
	BytesRx uint64 `protobuf:"varint,11,opt,name=bytes_rx,json=bytesRx,proto3" json:"bytes_rx,omitempty"`
	// MCP-specific (optional)
	McpToolName string `protobuf:"bytes,12,opt,name=mcp_tool_name,json=mcpToolName,proto3" json:"mcp_tool_name,omitempty"`
	// Process context
	Pid uint32 `protobuf:"varint,13,opt,name=pid,proto3" json:"pid,omitempty"`
	// OTel-specific (populated when identity_type == OTEL)
	OtelService    string `protobuf:"bytes,14,opt,name=otel_service,json=otelService,proto3" json:"otel_service,omitempty"`            // resource.attributes["service.name"]
	OtelSignalType string `protobuf:"bytes,15,opt,name=otel_signal_type,json=otelSignalType,proto3" json:"otel_signal_type,omitempty"` // "traces", "metrics", or "logs"
	OtelSpanCount  uint32 `protobuf:"varint,16,opt,name=otel_span_count,json=otelSpanCount,proto3" json:"otel_span_count,omitempty"`   // number of ResourceSpans/ResourceMetrics/ResourceLogs
	// Policy-specific (populated when event_type == POLICY_VIOLATION)
	PolicyRule string `protobuf:"bytes,17,opt,name=policy_rule,json=policyRule,proto3" json:"policy_rule,omitempty"` // Rego rule that triggered the violation
	// Boundary session correlation (populated when a Boundary token is observed in headers)
	BoundarySessionToken string `protobuf:"bytes,22,opt,name=boundary_session_token,json=boundarySessionToken,proto3" json:"boundary_session_token,omitempty"` // raw token value (at_*, s_*, or opaque UUID)
	BoundaryTokenType    string `protobuf:"bytes,23,opt,name=boundary_token_type,json=boundaryTokenType,proto3" json:"boundary_token_type,omitempty"`          // "auth", "session", or "opaque"
	// Cert rotation fields (populated when event_type == CERT_ROTATION_*)
	CertSerial            string                 `protobuf:"bytes,18,opt,name=cert_serial,json=certSerial,proto3" json:"cert_serial,omitempty"`                                    // hex-encoded certificate serial number
	CertExpiry            *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=cert_expiry,json=certExpiry,proto3" json:"cert_expiry,omitempty"`                                    // certificate NotAfter
	CertIssuerFingerprint string                 `protobuf:"bytes,20,opt,name=cert_issuer_fingerprint,json=certIssuerFingerprint,proto3" json:"cert_issuer_fingerprint,omitempty"` // SHA-256 of issuer public key (hex)
	PrevCertSerial        string                 `protobuf:"bytes,21,opt,name=prev_cert_serial,json=prevCertSerial,proto3" json:"prev_cert_serial,omitempty"`                      // previous serial (for diff on rotation events)
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ReflectorEvent) Reset() {
	*x = ReflectorEvent{}
	mi := &file_api_v1_reflector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReflectorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReflectorEvent) ProtoMessage() {}

func (x *ReflectorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_reflector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReflectorEvent.ProtoReflect.Descriptor instead.
func (*ReflectorEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_reflector_proto_rawDescGZIP(), []int{0}
}

func (x *ReflectorEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReflectorEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ReflectorEvent) GetEventType() ReflectorEvent_EventType {
	if x != nil {
		return x.EventType
	}
	return ReflectorEvent_CONNECTION_OPEN
}

func (x *ReflectorEvent) GetSourceAddr() string {
	if x != nil {
		return x.SourceAddr
	}
	return ""
}

func (x *ReflectorEvent) GetDestAddr() string {
	if x != nil {
		return x.DestAddr
	}
	return ""
}

func (x *ReflectorEvent) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ReflectorEvent) GetSourceIdentity() string {
	if x != nil {
		return x.SourceIdentity
	}
	return ""
}

func (x *ReflectorEvent) GetDestIdentity() string {
	if x != nil {
		return x.DestIdentity
	}
	return ""
}

func (x *ReflectorEvent) GetIdentityType() ReflectorEvent_IdentityType {
	if x != nil {
		return x.IdentityType
	}
	return ReflectorEvent_UNKNOWN
}

func (x *ReflectorEvent) GetBytesTx() uint64 {
	if x != nil {
		return x.BytesTx
	}
	return 0
}

func (x *ReflectorEvent) GetBytesRx() uint64 {
	if x != nil {
		return x.BytesRx
	}
	return 0
}

func (x *ReflectorEvent) GetMcpToolName() string {
	if x != nil {
		return x.McpToolName
	}
	return ""
}

func (x *ReflectorEvent) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ReflectorEvent) GetOtelService() string {
	if x != nil {
		return x.OtelService
	}
	return ""
}

func (x *ReflectorEvent) GetOtelSignalType() string {
	if x != nil {
		return x.OtelSignalType
	}
	return ""
}

func (x *ReflectorEvent) GetOtelSpanCount() uint32 {
	if x != nil {
		return x.OtelSpanCount
	}
	return 0
}

func (x *ReflectorEvent) GetPolicyRule() string {
	if x != nil {
		return x.PolicyRule
	}
	return ""
}

func (x *ReflectorEvent) GetBoundarySessionToken() string {
	if x != nil {
		return x.BoundarySessionToken
	}
	return ""
}

func (x *ReflectorEvent) GetBoundaryTokenType() string {
	if x != nil {
		return x.BoundaryTokenType
	}
	return ""
}

func (x *ReflectorEvent) GetCertSerial() string {
	if x != nil {
		return x.CertSerial
	}
	return ""
}

func (x *ReflectorEvent) GetCertExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.CertExpiry
	}
	return nil
}

func (x *ReflectorEvent) GetCertIssuerFingerprint() string {
	if x != nil {
		return x.CertIssuerFingerprint
	}
	return ""
}

func (x *ReflectorEvent) GetPrevCertSerial() string {
	if x != nil {
		return x.PrevCertSerial
	}
	return ""
}

// WorkerCommand is sent from sidecar to reflector.
// Empty in crawl. Walk adds enforce/release commands.
type WorkerCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerCommand) Reset() {
	*x = WorkerCommand{}
	mi := &file_api_v1_reflector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerCommand) ProtoMessage() {}

func (x *WorkerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_reflector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerCommand.ProtoReflect.Descriptor instead.
func (*WorkerCommand) Descriptor() ([]byte, []int) {
	return file_api_v1_reflector_proto_rawDescGZIP(), []int{1}
}

var File_api_v1_reflector_proto protoreflect.FileDescriptor

const file_api_v1_reflector_proto_rawDesc = "" +
	"\n" +
	"\x16api/v1/reflector.proto\x12\x11ebpf.reflector.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf6\t\n" +
	"\x0eReflectorEvent\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12J\n" +
	"\n" +
	"event_type\x18\x03 \x01(\x0e2+.ebpf.reflector.v1.ReflectorEvent.EventTypeR\teventType\x12\x1f\n" +
	"\vsource_addr\x18\x04 \x01(\tR\n" +
	"sourceAddr\x12\x1b\n" +
	"\tdest_addr\x18\x05 \x01(\tR\bdestAddr\x12\x1a\n" +
	"\bprotocol\x18\x06 \x01(\tR\bprotocol\x12'\n" +
	"\x0fsource_identity\x18\a \x01(\tR\x0esourceIdentity\x12#\n" +
	"\rdest_identity\x18\b \x01(\tR\fdestIdentity\x12S\n" +
	"\ridentity_type\x18\t \x01(\x0e2..ebpf.reflector.v1.ReflectorEvent.IdentityTypeR\fidentityType\x12\x19\n" +
	"\bbytes_tx\x18\n" +
	" \x01(\x04R\abytesTx\x12\x19\n" +
	"\bbytes_rx\x18\v \x01(\x04R\abytesRx\x12\"\n" +
	"\rmcp_tool_name\x18\f \x01(\tR\vmcpToolName\x12\x10\n" +
	"\x03pid\x18\r \x01(\rR\x03pid\x12!\n" +
	"\fotel_service\x18\x0e \x01(\tR\votelService\x12(\n" +
	"\x10otel_signal_type\x18\x0f \x01(\tR\x0eotelSignalType\x12&\n" +
	"\x0fotel_span_count\x18\x10 \x01(\rR\rotelSpanCount\x12\x1f\n" +
	"\vpolicy_rule\x18\x11 \x01(\tR\n" +
	"policyRule\x124\n" +
	"\x16boundary_session_token\x18\x16 \x01(\tR\x14boundarySessionToken\x12.\n" +
	"\x13boundary_token_type\x18\x17 \x01(\tR\x11boundaryTokenType\x12\x1f\n" +
	"\vcert_serial\x18\x12 \x01(\tR\n" +
	"certSerial\x12;\n" +
	"\vcert_expiry\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"certExpiry\x126\n" +
	"\x17cert_issuer_fingerprint\x18\x14 \x01(\tR\x15certIssuerFingerprint\x12(\n" +
	"\x10prev_cert_serial\x18\x15 \x01(\tR\x0eprevCertSerial\"\xda\x01\n" +
	"\tEventType\x12\x13\n" +
	"\x0fCONNECTION_OPEN\x10\x00\x12\x14\n" +
	"\x10CONNECTION_CLOSE\x10\x01\x12\x11\n" +
	"\rDATA_EXCHANGE\x10\x02\x12\x12\n" +
	"\x0eSTREAM_RESUMED\x10\x03\x12\x14\n" +
	"\x10POLICY_VIOLATION\x10\x04\x12\x18\n" +
	"\x14CERT_ROTATION_NORMAL\x10\x05\x12\x17\n" +
	"\x13CERT_ROTATION_EARLY\x10\x06\x12\x18\n" +
	"\x14CERT_ROTATION_ISSUER\x10\a\x12\x18\n" +
	"\x14CERT_ROTATION_DOMAIN\x10\b\"C\n" +
	"\fIdentityType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06SPIFFE\x10\x01\x12\a\n" +
	"\x03JWT\x10\x02\x12\a\n" +
	"\x03MCP\x10\x03\x12\b\n" +
	"\x04OTEL\x10\x04\"\x0f\n" +
	"\rWorkerCommand2k\n" +
	"\x10ReflectorService\x12W\n" +
	"\fStreamEvents\x12!.ebpf.reflector.v1.ReflectorEvent\x1a .ebpf.reflector.v1.WorkerCommand(\x010\x01B7Z5github.com/raygj/workload-ebpf-reflector/api/v1;apiv1b\x06proto3"

var (
	file_api_v1_reflector_proto_rawDescOnce sync.Once
	file_api_v1_reflector_proto_rawDescData []byte
)

func file_api_v1_reflector_proto_rawDescGZIP() []byte {
	file_api_v1_reflector_proto_rawDescOnce.Do(func() {
		file_api_v1_reflector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_reflector_proto_rawDesc), len(file_api_v1_reflector_proto_rawDesc)))
	})
	return file_api_v1_reflector_proto_rawDescData
}

var file_api_v1_reflector_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_v1_reflector_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_reflector_proto_goTypes = []any{
	(ReflectorEvent_EventType)(0),    // 0: ebpf.reflector.v1.ReflectorEvent.EventType
	(ReflectorEvent_IdentityType)(0), // 1: ebpf.reflector.v1.ReflectorEvent.IdentityType
	(*ReflectorEvent)(nil),           // 2: ebpf.reflector.v1.ReflectorEvent
	(*WorkerCommand)(nil),            // 3: ebpf.reflector.v1.WorkerCommand
	(*timestamppb.Timestamp)(nil),    // 4: google.protobuf.Timestamp
}
var file_api_v1_reflector_proto_depIdxs = []int32{
	4, // 0: ebpf.reflector.v1.ReflectorEvent.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: ebpf.reflector.v1.ReflectorEvent.event_type:type_name -> ebpf.reflector.v1.ReflectorEvent.EventType
	1, // 2: ebpf.reflector.v1.ReflectorEvent.identity_type:type_name -> ebpf.reflector.v1.ReflectorEvent.IdentityType
	4, // 3: ebpf.reflector.v1.ReflectorEvent.cert_expiry:type_name -> google.protobuf.Timestamp
	2, // 4: ebpf.reflector.v1.ReflectorService.StreamEvents:input_type -> ebpf.reflector.v1.ReflectorEvent
	3, // 5: ebpf.reflector.v1.ReflectorService.StreamEvents:output_type -> ebpf.reflector.v1.WorkerCommand
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_v1_reflector_proto_init() }
func file_api_v1_reflector_proto_init() {
	if File_api_v1_reflector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_reflector_proto_rawDesc), len(file_api_v1_reflector_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_reflector_proto_goTypes,
		DependencyIndexes: file_api_v1_reflector_proto_depIdxs,
		EnumInfos:         file_api_v1_reflector_proto_enumTypes,
		MessageInfos:      file_api_v1_reflector_proto_msgTypes,
	}.Build()
	File_api_v1_reflector_proto = out.File
	file_api_v1_reflector_proto_goTypes = nil
	file_api_v1_reflector_proto_depIdxs = nil
}
