// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/v1/reflector.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReflectorService_StreamEvents_FullMethodName = "/ebpf.reflector.v1.ReflectorService/StreamEvents"
)

// ReflectorServiceClient is the client API for ReflectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ReflectorService streams identity metadata from eBPF reflectors
// to the reflector-map sidecar. Bidirectional: reflector pushes events,
// sidecar can push commands back (empty in crawl, enforce in walk).
// ADR-003.
type ReflectorServiceClient interface {
	StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReflectorEvent, WorkerCommand], error)
}

type reflectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReflectorServiceClient(cc grpc.ClientConnInterface) ReflectorServiceClient {
	return &reflectorServiceClient{cc}
}

func (c *reflectorServiceClient) StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReflectorEvent, WorkerCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ReflectorService_ServiceDesc.Streams[0], ReflectorService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReflectorEvent, WorkerCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReflectorService_StreamEventsClient = grpc.BidiStreamingClient[ReflectorEvent, WorkerCommand]

// ReflectorServiceServer is the server API for ReflectorService service.
// All implementations must embed UnimplementedReflectorServiceServer
// for forward compatibility.
//
// ReflectorService streams identity metadata from eBPF reflectors
// to the reflector-map sidecar. Bidirectional: reflector pushes events,
// sidecar can push commands back (empty in crawl, enforce in walk).
// ADR-003.
type ReflectorServiceServer interface {
	StreamEvents(grpc.BidiStreamingServer[ReflectorEvent, WorkerCommand]) error
	mustEmbedUnimplementedReflectorServiceServer()
}

// UnimplementedReflectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReflectorServiceServer struct{}

func (UnimplementedReflectorServiceServer) StreamEvents(grpc.BidiStreamingServer[ReflectorEvent, WorkerCommand]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedReflectorServiceServer) mustEmbedUnimplementedReflectorServiceServer() {}
func (UnimplementedReflectorServiceServer) testEmbeddedByValue()                          {}

// UnsafeReflectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReflectorServiceServer will
// result in compilation errors.
type UnsafeReflectorServiceServer interface {
	mustEmbedUnimplementedReflectorServiceServer()
}

func RegisterReflectorServiceServer(s grpc.ServiceRegistrar, srv ReflectorServiceServer) {
	// If the following call panics, it indicates UnimplementedReflectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReflectorService_ServiceDesc, srv)
}

func _ReflectorService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReflectorServiceServer).StreamEvents(&grpc.GenericServerStream[ReflectorEvent, WorkerCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReflectorService_StreamEventsServer = grpc.BidiStreamingServer[ReflectorEvent, WorkerCommand]

// ReflectorService_ServiceDesc is the grpc.ServiceDesc for ReflectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReflectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ebpf.reflector.v1.ReflectorService",
	HandlerType: (*ReflectorServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _ReflectorService_StreamEvents_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/v1/reflector.proto",
}
