// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type certHookD2iArgs struct {
	_   structs.HostLayout
	InP uint64
	Len uint32
	Pad uint32
}

// loadCertHook returns the embedded CollectionSpec for certHook.
func loadCertHook() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CertHookBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load certHook: %w", err)
	}

	return spec, err
}

// loadCertHookObjects loads certHook and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*certHookObjects
//	*certHookPrograms
//	*certHookMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCertHookObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCertHook()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// certHookSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type certHookSpecs struct {
	certHookProgramSpecs
	certHookMapSpecs
	certHookVariableSpecs
}

// certHookProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type certHookProgramSpecs struct {
	UprobeD2iX509    *ebpf.ProgramSpec `ebpf:"uprobe_d2i_x509"`
	UretprobeD2iX509 *ebpf.ProgramSpec `ebpf:"uretprobe_d2i_x509"`
}

// certHookMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type certHookMapSpecs struct {
	CertEvents *ebpf.MapSpec `ebpf:"cert_events"`
	D2iActive  *ebpf.MapSpec `ebpf:"d2i_active"`
}

// certHookVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type certHookVariableSpecs struct {
}

// certHookObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCertHookObjects or ebpf.CollectionSpec.LoadAndAssign.
type certHookObjects struct {
	certHookPrograms
	certHookMaps
	certHookVariables
}

func (o *certHookObjects) Close() error {
	return _CertHookClose(
		&o.certHookPrograms,
		&o.certHookMaps,
	)
}

// certHookMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCertHookObjects or ebpf.CollectionSpec.LoadAndAssign.
type certHookMaps struct {
	CertEvents *ebpf.Map `ebpf:"cert_events"`
	D2iActive  *ebpf.Map `ebpf:"d2i_active"`
}

func (m *certHookMaps) Close() error {
	return _CertHookClose(
		m.CertEvents,
		m.D2iActive,
	)
}

// certHookVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCertHookObjects or ebpf.CollectionSpec.LoadAndAssign.
type certHookVariables struct {
}

// certHookPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCertHookObjects or ebpf.CollectionSpec.LoadAndAssign.
type certHookPrograms struct {
	UprobeD2iX509    *ebpf.Program `ebpf:"uprobe_d2i_x509"`
	UretprobeD2iX509 *ebpf.Program `ebpf:"uretprobe_d2i_x509"`
}

func (p *certHookPrograms) Close() error {
	return _CertHookClose(
		p.UprobeD2iX509,
		p.UretprobeD2iX509,
	)
}

func _CertHookClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed certhook_x86_bpfel.o
var _CertHookBytes []byte
