// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tcDropFlowKey struct {
	_        structs.HostLayout
	SrcIp    uint32
	DstIp    uint32
	DstPort  uint16
	Protocol uint8
	Pad      uint8
}

// loadTcDrop returns the embedded CollectionSpec for tcDrop.
func loadTcDrop() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcDropBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcDrop: %w", err)
	}

	return spec, err
}

// loadTcDropObjects loads tcDrop and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcDropObjects
//	*tcDropPrograms
//	*tcDropMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcDropObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcDrop()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcDropSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcDropSpecs struct {
	tcDropProgramSpecs
	tcDropMapSpecs
	tcDropVariableSpecs
}

// tcDropProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcDropProgramSpecs struct {
	TcDropEgress  *ebpf.ProgramSpec `ebpf:"tc_drop_egress"`
	TcDropIngress *ebpf.ProgramSpec `ebpf:"tc_drop_ingress"`
}

// tcDropMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcDropMapSpecs struct {
	DenyMap *ebpf.MapSpec `ebpf:"deny_map"`
}

// tcDropVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcDropVariableSpecs struct {
}

// tcDropObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcDropObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcDropObjects struct {
	tcDropPrograms
	tcDropMaps
	tcDropVariables
}

func (o *tcDropObjects) Close() error {
	return _TcDropClose(
		&o.tcDropPrograms,
		&o.tcDropMaps,
	)
}

// tcDropMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcDropObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcDropMaps struct {
	DenyMap *ebpf.Map `ebpf:"deny_map"`
}

func (m *tcDropMaps) Close() error {
	return _TcDropClose(
		m.DenyMap,
	)
}

// tcDropVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcDropObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcDropVariables struct {
}

// tcDropPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcDropObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcDropPrograms struct {
	TcDropEgress  *ebpf.Program `ebpf:"tc_drop_egress"`
	TcDropIngress *ebpf.Program `ebpf:"tc_drop_ingress"`
}

func (p *tcDropPrograms) Close() error {
	return _TcDropClose(
		p.TcDropEgress,
		p.TcDropIngress,
	)
}

func _TcDropClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcdrop_arm64_bpfel.o
var _TcDropBytes []byte
